---
title: "Untitled"
output: github_document
---{r}
#------------데이터 처리함수------------#

# head(데이터) : 데이터의 앞부분을 보여준다.
head(iris)

# tail(데이터) : 데이터의 뒷부분을 보여준다.
tail(iris)

# View(데이터) : 데이터 내용을 새 윈도우를 열어서 보여준다.
View(iris) # 오름차순으로 각 COL 을 정렬시켜볼수도 있고 아주 다양하다.

# dim(데이터) : 데이터의 차원
dim(iris)

# length(데이터) : 테이터의 element 갯수
length(iris) # 데이터 프레임에 사용시 column의 갯수
length(iris$Sepal.Length) # col 에 사용시 element 의 갯수

# names(데이터) : 데이터의 구성요소 이름 (col 의 이름)
names(iris)

# summary(데이터) : 데이터의 기초 통계량을 보여준다.
summary(iris)

# class(데이터) 데이터의 속성 
class(iris) # iris 의 속성은 data.frame
class(c(1,2,3)) # 벡터는 한 속성의 element로 구성된다. 즉 vector 의 구성인 numeric 표출
class(c(1,2,'a')) # 벡터는 한 속성의 element 가 되야되서 character 표출

# str(데이터) : 데이터의 내부 구조를 보여준다.
str(iris) # 범주형의 경우 어떤 level 로 구성되어있고, 각 data type 이 뭔지

# attach(데이터) : 데이터를 고정해서 사용한다.
attach(iris)
Sepal.Length # 원래 iris@Sepal.Length 로 해야하지만, attcach 로 해서 바로나온다.

# detach(데이터) : 데이터 고정을 해재한다.
detach(iris)
# Sepal.Length # 이렇게 실행하면 오류가 난다.
iris$Sepal.Length 

# with(데이터) : 데이터를 활성화한다. attach 와 비슷
with(iris,max(Sepal.Length))

#------------R 의 데이터구조------------#
# scala : 구성인자가 하나인 벡터
c(1)

# vector 
# vector : 구성인자가 1개 이상/ 1차원 ( 벡터중에서 구성인자가 1개면 scala)
# vector 들은 동질적이다. 즉 한 벡터의 모든 원소들은 같은 자료형을 가여야 한다.
c(1,2,3) # 이렇게 수행되면 동일한 숫자의 자료형을 가지게 된다.
c(1,'tom',3) # 이렇게 수행되면 string(문자) 의 동일한 자료형을 가지게 된다.
x <- c('a','b','c')
x[c(1,2)] # 인덱스를 통해 하위 벡터 반환 가능
names(x) <- c('first','second','third') # 이와 같이 벡터에 이름을 부여할 수 있다.
x['first'] # 그에 따라 이름을 가진 vector 가 만들어진다.

# list
# 생각보다 자주 사용되지는 않는다.
# list 자료형을 사용할경우 서로 다른 타입들의 변수를 가져다가 붙일 수 있다.
# 그리고 서로 다른 길이, 서로 다른 차원으로 구성될 수 있다.
school <- list(name = c('han','kim','hyo'),
              address = c('seoul','USA'),
              age = c(24))
# list 를 입력할때에는 위 처럼 = 를 사용해야 한다.
school # 위와 같이 class 라는 list 안에 또 다른 list 형성 가능.
# $로 접근하는 list
school$name # schoole 에서 name 의 '구성성분 추출'
# [[]] 로 접근하는 list 구성성분 추출
school[['name']]  # 'name' 의 구성성분 추출
school[[1]] # name(첫번쨰) 의 구성성분 추출
#[] 로 접근하는 ' sub list' 추출
school['name']
school[1]
#[[]] 와 [] 의 차이
class(school[1]) # sublist 추출 
class(school[[1]]) # list 에서 1번째 sublist 의 구성성분 추출

# array(배열) : 동일한 유형의 데이터가 2차원 이상으로 구성
array1 = array(1:24,c(2,3,4)) # 2*3*4 array
array1
array1[1,2,3]  # 1row,2col,3번쨰 행렬 추출

# Matrix(행렬) : 동일한 유형의 2차원 데이터
# 행렬은 모든 element 의 값들이 같은 형태여야 합니다. 
# 즉 1,2,3,'no' 의 4개 element 로 구성되어있는 vector 를 matrix 로 변환시 '1','2','3','no' 로 강제형변환이 됩니다.

matrix(1:12,nrow=3)
# nrow : row 의 수
# ncol : col 의 수
# dimnames : 행과 열에 이름을 부여 (이때 다른 길이를 쓸 수 있는 list 를 써야한다.)
matrix(1:12,nrow=3,dimnames = list(c('a','b','c'),c('1','2','3','4')))
# byrow : 가로로 먼저 채워지게 한다. default 는 세로(col)
matrix(1:12,nrow=3)
matrix(1:12,nrow=3,byrow=TRUE)
mat <- matrix(1:12,nrow=3,
              byrow = TRUE,
              dimnames = list(c('a','b','c'),c('1','2','3','4'))) ; mat
mat[6] # 그냥 6번째로 index 를 주게되면 col 부터 세게 되므로 10을 추출
mat[2,3] # 2row, 3col 의 값
mat['a','2'] # 이름으로도 추출 가능
mat[1:3,1] # 범위를 추출 가능
mat[c(1,3),c(2,4)] # vector 를 이용해 추출 가능
mat['a',c(3,1)] # 이름과 같이 추출 가능

# factor
# factor(요인) : 범주형(명목/순서)의 데이터구조
# 요인이 가질 수 있는값들을 수준(level) 이라고 한다.
# 펙터는 레벨을 알파벳 순으로 정렬한다. 
# 그 다음 알파벳 순의 레벨의 정수 인덱스로 벡터 내용을 다시 만든다.
# 펙터의 실제 내용은 레벨의 정수 인덱스이고, 각 정수를 레벨명으로 해독 가능한 범례가 있다고 생각하면 쉽다.
data = c('c','a','b')
example = factor(data)
as.numeric(example) 
# 위를 보면 3,1,2 로 되어있음을 볼 수 있다.
# 즉 알파벳 순으로 factor 를 지정해준것 
# 아래와 같이 하면 c,b,a 순으로 1,2,3 의 값을 매기고 ordered 가 c<b<a 로 된다.
# 즉 ordered data 를 만들고 싶을때 쓰게 된다.
factor(data,levels=c('c','b','a'),ordered = T) 


# dataframe(데이터프레임) : 데이터 유형에 상관없는 2차원데이터
name <- c('john','kim','marry')
age <- c(45,44,22)
child <- c(T,T,F)
df <- data.frame(name,age,child) ; df
str(df)

#-------------데이터 구조 함수----------#
#--왜 해야하나요?--#
library(MASS)
str(Cars93) # 데이터의 속성을 잘 확인하여야, 
# 1.각 데이터 속성에 맞는 함수를 적용가능
# 2.데이터별 속성이 잘못 들어가있을수도 있다. (숫자형이 factor 라든지...)

# as.factor(데이터) : 데이터를 factor 로 변환해준다.
x <- c('A','B','C')
factor_x <- as.factor(x)
str(factor_x) # level이 생긴 factor 형태가 된 것을 볼 수 있다.

# as.numeric(데이터) : 데이터를 숫자로 변환한다.
x <- c('4','5','10')
str(x) # chr 의 데이터 tpye
numeric_x <- as.numeric(x)
str(numeric_x) # chr -> num 으로 데이터 type 이 바뀐것을 볼 수 있다.

# as.character(데이터) : 데이터를 chr 로 변환
as.character(3.14)

# as.vector(데이터) : 데이터를 vector 로 변환
as.vector('C')

# as.logical(데이터) : logic 값으로 변환
as.logical(3.42) # 이때에 0 일때에만 False 를 내보내고 나머지 경우는 True 를 나타낸다. 
as.integer(3.2)
as.numeric('go') # 바꿀수 없는 경우 에러가 뜬다.
as.character(100)
as.numeric(FALSE) # FALSE 인 경우 0 

