---
title: "데이터 전처리1"
output: github_document
editor_options: 
  chunk_output_type: console
---
# 년,월,일 나누기[substr]
아래와 같이 dataframe 에서 연월일이 붙어있는 경우가 있가. <br>
그런 경우에는 substr 을 이용하여 앞의 몇개만 떼어네서 데이터를 새로 만들 수 있다. <br>
```{r}
time <- c(20210101,20210302,20210401,20211230)
sell <- c(134,253,213,223)
df <- data.frame(time,sell) ;df 
df$year <- substr(df$time,1,4)
df$month <- substr(df$time,5,6)
df$day <- substr(df$time,7,8)
df
```
위와 같이 substr 을 이용하여 연,월,일을 만들어내었다.

# 문자형 벡터 붙이기[paste]
위에서 생성한 df 의 년,월,일에 각각 년,월,일 의 문자를 붙이고 싶다고 하자. <br>
그러면 이 떄 paste 를 이용해서 붙일 수 있다.
```{r}
df$year = paste(df$year,'년')
df$month = paste(df$month,'월')
df$day = paste(df$day,'일')
df
```

# 문자열 특정 문자 모두 지우기
이 dataset 에서 . 을 모두 지우고싶다고 하자.
```{r}
id <- c('a','b','c','d')
kg <- c(134.4,23.2,44.2,32.1)
df <- data.frame(id,kg) ; df
df$kg = gsub('.','',df$kg,fixed = TRUE)
df
```


# 데이터 중복없이 unique 한 관측치만 선별하기 
duplicate 함수를 이용하여 중복되는 열은 제거할 수 있다. <br>
duplicated 는 중복값이 아닐때에 false 를 출력하고, 중복값이면(이전에 나왔으면) True 를 출력한다.

```{r}
a1 <- rep(1:10, each=2)
a2 <- rep(c(1,3,5,7,9),each=4)
a3 <- c(1,1,1,1,3,3,3,3,5,5,6,6,7,7,8,8,9,10,11,12)
df <- data.frame(cbind(a1,a2,a3)) ; df

# a1,a2의 두개 변수를 기준으로 중복 체크 후 중복이있을때는 1개만선텍
unique(df[,c('a1','a2')]) # df[,c('a1','a2')] : 변수a1,a2만 선택
df_new = df[duplicated(df[,c('a1','a2')]),] ; df_new
row.names(df_new) = NULL ; df_new # 꼭 index 를 초기화 하는 작업을 진행하자.
```