---
title: "기본적인 연산 및 통계함수"
output:
  github_document
editor_options:
  chunk_output_type: console
---
# 수학 함수
```{r}
abs(-10) # 절대값
sqrt(9) # 제곱근
ceiling(9.4) # 올림
floor(9.4) # 내림
round(9.45,1) # 소수점 n자리까지 반올림
log(100,base=10) # 밑이 10 인 log
log(2.718) # 자연로그
exp(2) # exponential 함수
factorial(3) 
diff(c(1,3,4,5),lag=1) # 차분
length(c(1,4,3,5)) #관측값 갯수
```
# 기술통계 함수
```{r}
x<-c(1,5,2,8,4) 
mean(x)   #평균
median(x) #중앙값값
var(x)    #분산
sd(x)     #표준편차
min(x)    #최소
max(x)    #최대
range(x)  #범위
length(x) #갯수 
cumsum(x) #벡터누적합
cumprod(x)#벡터누적곱
rank(x)   #순서
```
# 통계 분포 함수 
beta        : beta  (shape1 shape2) <br>
binomial    : binom (size prob) <br>
chi-square  : chisq (df) <br>
unif        : unif  (min max) <br>
exp         : exp   (rate) # $pdf=re^{(-rx)}$ <br> 
F           : f     (df1 df2) <br>
gamma       : gamma (shape rate(scale)) <br>
note: scale 에 대해 shape * scale 이 mean, shape * scale^2 이 var <br>
geometric   : geom  (prob) <br> 
normal      : norm  (mean sd) <br>
poisson     : pois  (lambda) <br>
T           : t     (df) <br>
<br>
d--- : pdf/pmf <br>
p--- : cdf <br>
q--- : quantile <br>
r--- : random sample <br>

```{r}
rnorm(100) # 100개의 N(0,1) sample
rexp(100,rate=1) 

dbinom(3,size=10,prob=0.25) # X ~ B(10,0.25) 에서 P(X=3)
dpois(0:2,lambda = 4) # X ~ pois(4) 에서 P(X=0,1,2)

pnorm(12,mean=10,sd=2) # X~N(10,4) 에서 P(X <= 12)

qt(0.95,df=20) # 95th percentile of t(20) 즉 왼쪽꼬리의 값이 0.95 
qt(0.05,df=20,lower.tail = F) # 즉 오른쪽 꼬리의 확률이 0.05
```

# 논리 연산
```{r}
x<-c(1:5) 
y<-c(5:1)

# elementwise 하게 수행이 된다.
x*y
x+y

#비교
x>=y
x<=y
x>y 
x!=y #서로 같지 않다.

#논리
(3 <= x) & (x <= 4) # and
(3 <= x) | (x <= 4) # or
any(3<=x) # 하나여도 맞으면 true
all(3<=x) # 모두 맞아야 true

```

# 특수 연산
```{r}
x
y
x%%3 #나머지
x%/%3 #몫
x%*%y #행렬곱
x%in%2 #벡터내 특정값 포함여부
```

#행렬 연산 함수
```{r}
A <- matrix(c(1,6,3,
              4,2,5,
              8,7,9), byrow=TRUE,nrow=3)
B <- matrix(c(1,1,1,
              -1,-1,-1,
              0,0,0),byrow=TRUE,nrow=3)
t(A) #transpose
diag(c(1,2,3,4)) #대각행렬
diag(4) #항등행렬
solve(A) #역행렬
det(A) #det
A*B # elementwise 연산
A%*%B # 행렬연산
# 1~10 의 vector 만들기
```

# 인덱싱
```{R}
x<-c(1:5) 
y<-c(5:1)
#x[i] : 벡터의 i번째 값을 보여준다.
x[2]

#x[i] <- 3 : 벡터의 i번째 값을 3 으로 치환한다.
x[2] = 99

#x[-i] : 벡터의 i번쨰 값을 없애고 보여준다.
x[-2]

#x[n:m] : 벡터의 n~m 값을 보여준다.
x[2:4]

#apppend(x,y) : x와y 를 연결한다.
append(x,y)
```

```{r}
x = c(1,2,3,4)
names(x) = c('a','b','c','d') # 이렇게 인덱싱을 달게되면
x[c(2,4)] # 위치로 인덱싱
x[c(-1,-3)] # - 값은 제외하여 인덱싱
x[c(TRUE,TRUE,FALSE,TRUE)] # T,F 로 인덱싱
x[c('a','c')] # names 했던 문자로 인덱싱
```

# 벡터의 집합연산
```{r}
x
y
union(x,y) #x,y 의 합집합
intersect(x,y) #x,y 의 교집합
setdiff(x,y) #x,y 의 차집합
```