---
title: "데이터 변환"
output: github_document
editor_options: 
  chunk_output_type: console
---
```{r}
student_id <- c("s01", "s02", "s03", "s04", "s05", "s06", "s07", "s08", "s09", "s10")
stat_score <- c(56, 94, 82, 70, 64, 82, 78, 80, 76, 78)
mean(stat_score)
hist(stat_score)
```

# 연속형 -> 범주형
ifelse 를 반복적으로 쓰게되면, 각 값마다 알맞게 범주형으로 고칠 수 있다.
```{r}
score_d.f <- data.frame(student_id, stat_score)
score_d.f
attach(score_d.f)
score_d.f <- transform(score_d.f, 
                       stat_score_5 = ifelse(stat_score < 60, "가", 
                                             ifelse(stat_score >= 60 & stat_score < 70, "양", 
                                                    ifelse(stat_score >= 70 & stat_score < 80, "미", 
                                                           ifelse(stat_score >= 80 & stat_score < 90, "우", "수")))))
detach(score_d.f)
score_d.f
```

# 데이터 정규화
평균0 분산1 의 데이터를 가지도록 정규화
```{r}
scale_score1= scale(score_d.f$stat_score)
scale_score1
attributes(scale_score1)
# 어떻게 표준화 시켰는지 알려준다.
# 이 값을 통해 표준화  하기 전 값으로 돌려갈 수있다.
```

# Min-max scailing 
[0,1] 사이의 값을 가지게 스케일링이 된다.
```{r}
# [0-1] 의 값을 가지도록 정규화
k = score_d.f$stat_score 
scale_score2 = (k- min(k))/(max(k)-min(k))
scale_score2
```

#log/sqrt 변환
주로 분산 안정화를 위해 사용.
```{r}
x = score_d.f$stat_score 
sqrt(x) 
log(1+x) # 로그는 0에 가깝게 되는 경우 inf 로 발산하기때문에 주로 1+x 변환을 쓴다.
```

